version: "3.8"

services:
  app:
    image: devarogundade/movecall-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PRIVATE_KEY=
      - SECRET_KEY=
      - PORT
    command: npx nodemon index.ts
